server:
  port: 4001

spring:
  application:
    name: @artifactId@
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        file-extension: yml
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#  profiles:
#    active: @profiles.active@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:123456}
      url: jdbc:mysql://${MYSQL-HOST:127.0.0.1}:${MYSQL-PORT:3306}/${MYSQL-DB:multitenant}?characterEncoding=utf8&&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        session_factory:
          statement_inspector: com.multi.tenant.multitenancy.TenantInterceptor

# 需进行租户解析的租户表
sys:
  tenant:
    ignore-table: